//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mtx.LearnItAll.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CoreMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoreMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mtx.LearnItAll.Core.Resources.CoreMessages", typeof(CoreMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided name is already in use..
        /// </summary>
        public static string AddPartResult_DuplicateSibling {
            get {
                return ResourceManager.GetString("AddPartResult_DuplicateSibling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot exceed {0} chars.
        /// </summary>
        public static string ModelName_CannotExceedMaximunLenght {
            get {
                return ResourceManager.GetString("ModelName_CannotExceedMaximunLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one operation failed while adding multiple parts: {0}.
        /// </summary>
        public static string Skill_AddingMultipleParts_Failed {
            get {
                return ResourceManager.GetString("Skill_AddingMultipleParts_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The part id provided does not exist in the current Skill..
        /// </summary>
        public static string Skill_ParentIdDoesNotExist {
            get {
                return ResourceManager.GetString("Skill_ParentIdDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Skill Model named {0} already exists in the Skill Model Set {1}.
        /// </summary>
        public static string SkillModel_ASkillWithSameNameAlreadyExistis {
            get {
                return ResourceManager.GetString("SkillModel_ASkillWithSameNameAlreadyExistis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name &apos;{0}&apos; is already in use by a sibling part under {1}.
        /// </summary>
        public static string SkillModel_CannotAddDuplicateNameForChildOnSameLevel {
            get {
                return ResourceManager.GetString("SkillModel_CannotAddDuplicateNameForChildOnSameLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Skill or any of its parts cannot have more than {0} direct children..
        /// </summary>
        public static string SkillModelSet_MaximumDirectSkillModelChildExceeded {
            get {
                return ResourceManager.GetString("SkillModelSet_MaximumDirectSkillModelChildExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one Skill Model is required.
        /// </summary>
        public static string SkillSetModel_AtLeastOneSkillModelRequired {
            get {
                return ResourceManager.GetString("SkillSetModel_AtLeastOneSkillModelRequired", resourceCulture);
            }
        }
    }
}
