//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mtx.LearnItAll.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mtx.LearnItAll.Core.Resources.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a I can use it, but most of the time I need help to apply and to understand it&apos;s concepts. I have limited or no professional experience. My knowledge covers few key features..
        /// </summary>
        public static string SkillLevel_AdvancedBeginner {
            get {
                return ResourceManager.GetString("SkillLevel_AdvancedBeginner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Most of the time I can use it to perform a task without resorting to help. I have practical experience that covers close to 80% if its scope..
        /// </summary>
        public static string SkillLevel_Competent {
            get {
                return ResourceManager.GetString("SkillLevel_Competent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a I master it. I am a reference in the skill inside and outside the organization I work for. I have consistent excellence in applying it accross multiple projects and/or organizations..
        /// </summary>
        public static string SkillLevel_Expert {
            get {
                return ResourceManager.GetString("SkillLevel_Expert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a I have an understanding of it&apos;s basic techniques or concepts..
        /// </summary>
        public static string SkillLevel_Novice {
            get {
                return ResourceManager.GetString("SkillLevel_Novice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a I don&apos;t need assistance with it. I am recognized as &quot;a person to ask&quot; when difficult questions arise regarding this skill. I can coach others in the application of this skill..
        /// </summary>
        public static string SkillLevel_Proficient {
            get {
                return ResourceManager.GetString("SkillLevel_Proficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a I don&apos;t understand what it is..
        /// </summary>
        public static string SkillLevel_Unfamiliar {
            get {
                return ResourceManager.GetString("SkillLevel_Unfamiliar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Unknown..
        /// </summary>
        public static string SkillLevel_Unknown {
            get {
                return ResourceManager.GetString("SkillLevel_Unknown", resourceCulture);
            }
        }
    }
}
